# github.com/go-task/task

build:
  cmds:
    - go build -o circle
dev:
  cmds:
    - ./circle --dbHost 127.0.0.1 --dbPort 3306 --dbName circle --dbUser root --dbPassword jjgo --circleID 1 --rootPath _example

gen:
  cmds:
    - ^build
    - ./circle --mode generate --circleID 1 --rootPath _example
  env:
    PRODENV: dev
    SECRET_KEY: superjjgo
    DB_HOST: 127.0.0.1
    DB_NAME: circle
    DB_USER: root
    DB_PASSWORD: olim

add:
  cmds:
    - ^build
    - ./circle --mode add --name Test --rootPath _example

delete:
  cmds:
    - ^build
    - ./circle --mode delete --name Test --rootPath _example

import:
  cmds:
    - ^build
    - ./circle --circleID 1 --dbHost 127.0.0.1 --dbPort 3306 --dbName circle --dbUser root --dbPassword olim --mode import --rootPath _example

dev-build:
  cmds:
    - ^build
    - ./circle --mode build --rootPath _example/beegoapp


test:
  cmds:
    - ^clean
    - go test *.go -v

clean:
  cmds:
    - rm ./circle
    - rm -rf _example/admin/*
    - rm -rf _example/controllers/*
    - rm -rf _example/models/*
    - rm -rf _example/requests/*
    - rm -rf _example/responses/*
    - rm -rf _example/routers/*