# github.com/go-task/task

test:
  cmds:
    - ^clean
    - go test *.go -v

clean:
  cmds:
    - rm -rf test/admin/*
    - rm -rf test/controllers/*
    - rm -rf test/models/*
    - rm -rf test/requests/*
    - rm -rf test/responses/*
    - rm -rf test/routers/*