# github.com/go-task/task

test:
  cmds:
    - ^clean
    - go test *.go -v

clean:
  cmds:
    - rm -rf example/admin/*
    - rm -rf example/controllers/*
    - rm -rf example/models/*
    - rm -rf example/requests/*
    - rm -rf example/responses/*
    - rm -rf example/routers/*