# github.com/go-task/task

dev:
  cmds:
    - go run ./cli.go ./circleManager.go --dbHost 127.0.0.1 --dbPort 3306 --dbName circle --dbUser root --dbPassword jjgo --circleID 1 --rootPath example

add:
  cmds:
    - go run ./cli.go ./circleManager.go --mode add --name Test --rootPath .example

test:
  cmds:
    - ^clean
    - go test *.go -v

clean:
  cmds:
    - rm -rf example/admin/*
    - rm -rf example/controllers/*
    - rm -rf example/models/*
    - rm -rf example/requests/*
    - rm -rf example/responses/*
    - rm -rf example/routers/*